### ISSUE TITLE
Pairing subfinder with active subdomain takeover sources

### ISSUE THREAD

**Issue by jaikishantulswani** [subfinder/subfinder#123]
Hello @Ice3man543 ,
Integrating SubOver in Subfinder become a great combo !

**Comment by codingo** [comment]
There's always the unix approach to consider - have each tool do one thing, and do it very well. Once we start integrating these kinds of features it takes aware from the core of subfinder: discovering subdomains.

I've spoken to a few people from other fields (marketing, for e.g.) using subfinder for tasks other than subdomain takeover discovery. I think that keeping this distinct difference is an important part of the project.

I'll leave this open in case any of the others disagree, but for my part, I think this would be against the projects intention.

**Comment by Ice3man543** [comment]
I agree with codingo. Which is why we haven't added subover yet. And probably will not do so in future too.
