### ISSUE TITLE
Implement Permutation Generation

### ISSUE THREAD

**Issue by Ice3man543** [subfinder/subfinder#125]
Implement permutations for subdomains like altdns does.

**Comment by madaratech** [comment]
Good to see you guys planning to improve the active bruting as well. 

Here is the [extended wordlist](https://github.com/haccer/altdns/blob/master/words.txt) I found for the AltDNS, just in case if it's helpful for this. 

Also what you guys think about recursive permutation generation?

for example with the help of permutation, the tool found `abc.xyx.test.com` do you think is it a good idea to again create all possible permutation for `abc.xyx.test.com` and resolved it again and do the same till no new subdomain discovered using permutation? surely bit more time-consuming process.

**Comment by bugbaba** [comment]
The major downside of permutations is **task of resolving them**.

For example there are `100` live subdomains and if we append it in this format `$var.sub.domain.tld` 
It will result in `3000` subs to resolve.

So considering the number of words in list  + the permutations 

It can easily reach upto 10K subs even for a regular site, resolving them might even crash the subfinder!

**Comment by Ice3man543** [comment]
Hey, goaltdns is what i recommend for alteration. Closing this issue now as this is outside the scope of subfinder.
