### ISSUE TITLE
QUESTION: 

### ISSUE THREAD

**Issue by whoot** [subfinder/subfinder#127]
Hey there,

in the readme you state:
**"We ensure that we abide by the terms and conditions of all sources that we query. For this reason we don't perform scraping on any site that doesn't allow it."**

However, Netcraft does not allow the usage of automated tools. The Netcraft website (https://www.netcraft.com/about-netcraft/fair-use-copyright/) states:
"_At Netcraft’s discretion any automated program (or particular network suspected of operating an automated program) may be blocked at any time.
Any use or attempted use of an automated program to access pages that are disallowed by Netcraft’s robots.txt file, or that fails to identify itself as an automated program, is strictly unauthorised and shall be a misuse of our system and this site._"

So isnt the usage of Netcraft in Subfinder prohibited?

**Comment by codingo** [comment]
Thank-you for bringing this to our attention. We'll raise it in our slack and remove it if so. We've done this before when terms of service for various programs changed, which is likely what has happened here.

**Comment by Ice3man543** [comment]
Thanks for this @whoot. I removed netcraft in commit 29d7ab941e2ff28d803de102bb9775996311470c.

**Comment by whoot** [comment]
It may also be useful to point out that some services are only intended for non-commercial use.
These include, for example:
 - certDB
 - certspotter

and others

**Comment by Ice3man543** [comment]
Hi again, I don't think this poses any risk on us (bug bounty hunters and infosec community) since we don't use it for commercial purposes. I don't think it'd be right to remove them.

**Comment by codingo** [comment]
I'll review this tomorrow, I'm not sure I entirely agree with the premise at face value. This isn't commercial software, not does our license consider it so.

Principally we ensure safe usage for an individual or a tester to allow active use of this application in a marketing role or on penetration tests where other software has been adding multiple sources that directly break ToS in these uses cases and become banned. 

I appreciate where you're coming from @whoot, but I don't believe it's in good faith with what expectations of this product and its license are assumed to be.
