### ISSUE TITLE
Installation error:

### ISSUE THREAD

**Issue by Tikam02** [subfinder/subfinder#129]
OS: Kali Linux

could not install or find any subfinder directory after it's installation through go.
@Ice3man543  Please provide built and install instructions.

![sub2](https://user-images.githubusercontent.com/10548085/44004230-e5ee3c08-9e7c-11e8-91d3-d68192a78f0a.png)

**Comment by picatz** [comment]
@Tikam02 👋 Hello!

If you have your `GOTPATH` properly setup and have `$GOAPTH/bin` in your `$PATH` envrioment variable, then you can just use SubFinder by calling it without the `./` part.

I suspect this is the case if `go get` works 👍 

## Example
```shell
$ subfinder -h
```
> *Note* the `$` is showing this should be run in a shell. 🐚 

Please let me know if that does't work 🙏

**Comment by Tikam02** [comment]
Thanks for the help @picatz   yup it's working now. :+1:

**Comment by picatz** [comment]
Awesome, glad to hear it @Tikam02!

**Comment by peaceasad** [comment]
after installing go properly, means I am able to see go version command result 
than I install subfinder with go command 

after installing subfinder 
subfinder is not found is  go/bin directory

**Comment by glaucusec** [comment]
> after installing go properly, means I am able to see go version command result than I install subfinder with go command
> 
> after installing subfinder subfinder is not found is go/bin directory

exact same issue. did you found a solution?
