### ISSUE TITLE
Client.Timeout exceeded

### ISSUE THREAD

**Issue by PjMpire** [subfinder/subfinder#140]
Im getting a tonne of these errors. and im not sure why.

At first i though it was my number of thread casuing issue so i reset to defautl but still getting same problem.

"Client.Timout exceeded while awaiting headers"

is this normal?

cheers

**Comment by HellboundTKR** [comment]
right so I tested with a fresh VM parrotOS and all was dandy at first until about 30 minutes ago

Im not getting the same error as another user who posted an issue about the same time the error popped up issue #141

**Comment by HellboundTKR** [comment]
Hi, I was getting errors whilst also getting some results. I made a fresh VM and this time it ran fine and I am not getting timeout errors anymore.

my using custom script  git pull domains into a list to be enumerated with subfinder. however I am now getting errors the same as issue #141.  Sometimes the script will run fine but if I run the same script again straight after a successful result  i get "anic while running job: runtime error: index out of range
panic: runtime error: index out of range"  2/5 times.

When that error pops up it halts the script, but if I run it again it works absolutely fine.

**Comment by PjMpire** [comment]
Cheers for the help and great work btw! 

Issue seems resolved now after issue  #141 fix updating golang.

This can be closed :)
