### ISSUE TITLE
subfinder is not working

### ISSUE THREAD

**Issue by aSIHADHASJDADSGAJD** [subfinder/subfinder#141]
2018/09/01 17:08:12 panic while running job: runtime error: index out of range
panic: runtime error: index out of range [recovered]
	panic: interface conversion: interface {} is runtime.errorString, not string

goroutine 32 [running]:
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker.func1(0xc42007aa50)
	/root/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:61 +0x163
panic(0x713700, 0x9299b0)
	/usr/lib/go-1.10/src/runtime/panic.go:502 +0x229
github.com/subfinder/subfinder/libsubfinder/sources/dnsdb.Query(0xc4200e6a00, 0x2, 0x2, 0x6a6f01, 0x940101)
	/root/go/src/github.com/subfinder/subfinder/libsubfinder/sources/dnsdb/dnsdb.go:53 +0x70e
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker(0xc420094b40, 0xc42007aa50)
	/root/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:64 +0x6e
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).worker(0xc420094b40, 0xd)
	/root/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:78 +0xb3
created by github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).Run
	/root/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:181 +0x7f

got this error message everytime

**Comment by HellboundTKR** [comment]
literally just started getting this error about 30 minutes ago an is the first time ive seen it

`panic: reflect: slice length out of range in SetLen [recovered]
	panic: interface conversion: string is not error: missing method Error [recovered]
	panic: interface conversion: interface {} is *runtime.TypeAssertionError, not string

goroutine 104140 [running]:
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker.func1(0xc42a52fd60)
	/root/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:61 +0x163
panic(0x719140, 0xc42ac08500)
	/usr/lib/go-1.10/src/runtime/panic.go:502 +0x229
encoding/json.(*decodeState).unmarshal.func1(0xc42642de08)
	/usr/lib/go-1.10/src/encoding/json/decode.go:177 +0x8f
panic(0x6ff940, 0x7b5be0)
	/usr/lib/go-1.10/src/runtime/panic.go:502 +0x229
reflect.Value.SetLen(0x6fbc40, 0x945700, 0x197, 0x157)
	/usr/lib/go-1.10/src/reflect/value.go:1467 +0x7f
encoding/json.(*decodeState).array(0xc42206de60, 0x6fbc40, 0x945700, 0x197)
	/usr/lib/go-1.10/src/encoding/json/decode.go:577 +0x5a7
encoding/json.(*decodeState).value(0xc42206de60, 0x6fbc40, 0x945700, 0x197)
	/usr/lib/go-1.10/src/encoding/json/decode.go:405 +0x266
encoding/json.(*decodeState).object(0xc42206de60, 0x6f1b60, 0x945700, 0x16)
	/usr/lib/go-1.10/src/encoding/json/decode.go:776 +0x132d
encoding/json.(*decodeState).value(0xc42206de60, 0x6f1b60, 0x945700, 0x16)
	/usr/lib/go-1.10/src/encoding/json/decode.go:408 +0x2d3
encoding/json.(*decodeState).unmarshal(0xc42206de60, 0x6f1b60, 0x945700, 0x0, 0x0)
	/usr/lib/go-1.10/src/encoding/json/decode.go:189 +0x1e7
encoding/json.Unmarshal(0xc422a40000, 0x3f9b, 0x7e00, 0x6f1b60, 0x945700, 0x0, 0x0)
	/usr/lib/go-1.10/src/encoding/json/decode.go:108 +0x148
github.com/subfinder/subfinder/libsubfinder/sources/threatcrowd.Query(0xc4276962e0, 0x2, 0x2, 0x68cc01, 0x101)
	/root/go/src/github.com/subfinder/subfinder/libsubfinder/sources/threatcrowd/threatcrowd.go:56 +0x23d
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker(0xc4247c8e60, 0xc42a52fd60)
	/root/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:64 +0x6e
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).worker(0xc4247c8e60, 0x3)
	/root/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:78 +0xb3
created by github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).Run
	/root/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:181 +0x7f
`

**Comment by picatz** [comment]
@aSIHADHASJDADSGAJD Can you confirm you're running the latest version of subfinder?

You can try updating with;
```shell
$ go get -u github.com/subfinder/subfinder
```

**Comment by HellboundTKR** [comment]
Found a fix for me using this automated script to update golang:

https://github.com/udhos/update-golang

USAGE:

git clone https://github.com/udhos/update-golang
cd update-golang
sudo ./update-golang.sh


Subfinder Chugs away nicely now :)

**Comment by picatz** [comment]
Cool find. 👍 

Going to close this issue now. 🙇
