### ISSUE TITLE
ReconJSON output format

### ISSUE THREAD

**Issue by quietsec** [subfinder/subfinder#146]
Heyo,

I recently found the `ReconJSON` json schema specification, which aims to define a standard export format for recon tools -- so you could take output from one tool and pipe it into the next.

Details about the spec can be found here: https://github.com/ReconJSON/ReconJSON

Is there any interest for including `ReconJSON` as a json output format? Perhaps with a `-oRJ` flag or something like that? Thoughts?

**Comment by quietsec** [comment]
For what it's worth, I have some noob-level golang skills I've been meaning to grow. So if there is interest for including this into subfinder, I would be happy to work on an implementation for it.

**Comment by quietsec** [comment]
Hey @Ice3man543,

Ah, you appear to be correct! The github issues for the ReconJSON project make things sound like most of the spec is still a work-in-progress. My mistake, I had just read a few of the files and thought they sounded reasonable -- but probably best to hold off until the spec is fully ironed out before including it here. I'll close this issue for now.

---

Also I just recently found subfinder, and I'm not aware of any of the v2 features -- are they documented anywhere? Are there any low-hanging fruit features that need help/contributions? Like I said above, I'm interested in learning more golang, and this seems like a great project to contribute to.

**Comment by Ice3man543** [comment]
@quietsec Do you use slack? I can add you to our slack. 
We can talk there. Honestly, github issues seem worst place to talk! :+1:

**Comment by quietsec** [comment]
@Ice3man543 Yup, you should be able to invite quietsec@protonmail.com
