### ISSUE TITLE
Invalid Argument On Some Source

### ISSUE THREAD

**Issue by anazu** [subfinder/subfinder#147]
hello
when i try to Running enumeration on any domain then i get this error
some time its failed to connect shodan and some time "Ask" and some time other source 
output error: connect: invalid argument

[
![capture](https://user-images.githubusercontent.com/40093902/46905571-9d984680-cf17-11e8-856e-f6b4e8e4f5ff.PNG)
](url)

**Comment by Mzack9999** [comment]
Hello @anasalzuvix , thanks for reporting this.
From the picture it looks like the issue is related to the system not being able to lookup addresses. if you execute from the shell any lookup, does it work correctly?
Eg.

`$ nslookup www.dogpile.com`
