### ISSUE TITLE
Add Support for: pkey.in and pentest-tools.com

### ISSUE THREAD

**Issue by ZeroDot1** [subfinder/subfinder#149]
I don't know if these pages are very useful, but I just suggest them.
https://www.pkey.in/tools-i/search-subdomains
https://pentest-tools.com/information-gathering/find-subdomains-of-domain

**Comment by Ice3man543** [comment]
@ZeroDot1 I agree with @bugbaba. It's a commercial service + I don't know what it uses internally but I am pretty sure I used it in past and got much less results. 

Thanks.

**Comment by Ice3man543** [comment]
Closing this issue now as both are commercial services and don't offer much in terms of good results!
