### ISSUE TITLE
Crtsh error

### ISSUE THREAD

**Issue by Iamanoobs** [subfinder/subfinder#155]
**HI.** Been using subfinder for many months now. Tried updating it recently and I think it is getting crt.sh error. No crt.sh are also showing in the result (running source)

 I am getting this error:

`crtsh: json: cannot unmarshal array into Go value of type crtsh.crtshObject`

Thanks

**Comment by Iamanoobs** [comment]
dnsdb error (503) also occurs, is it my internet connection fault?

**Comment by ggranjus** [comment]
For crtsh, the source output has changed: https://github.com/subfinder/subfinder/pull/156

**Comment by Ice3man543** [comment]
Hey, this has been fixed! Thanks for notifying
