### ISSUE TITLE
DNSDB Source no longer works

### ISSUE THREAD

**Issue by lc** [subfinder/subfinder#161]
## What's the problem (or question)?
The [endpoint](https://github.com/subfinder/subfinder/blob/master/libsubfinder/sources/dnsdb/dnsdb.go#L32) subfinder requests on DNSDB now always responds with an unexpected response due to their CloudFlare implementation

## Do you have an idea for a solution?
Not at the moment.

## How can we reproduce the issue?
1. Visit: https://github.com/subfinder/subfinder/blob/master/libsubfinder/sources/dnsdb/dnsdb.go#L32
2. Make a valid request to the endpoint with curl: 

```
curl -s 'http://www.dnsdb.org/f/yahoo.com.dnsdb.org/' -v | grep '503'
```

You'll receive the following response: `503 Service Temporarily Unavailable`

**Comment by Ice3man543** [comment]
Hi @C0RB3N,

DNSDB has added CloudFlare as you said that causes  the tool to fail parsing it.

Thanks for notifying us, should be removed soon. Things have been delayed much due to life :)

**Comment by jaherne** [comment]
It looks like dnsdb exposes an API at https://api.dnsdb.info/, but this requires an API key. It might be worth exploring adding support for that similar to the Shodan source. Or dnsdb can just be removed entirely.

**Comment by Ice3man543** [comment]
Hey, this is getting deleted in the future. Closing the issue now!
