### ISSUE TITLE
Api key load balancing.

### ISSUE THREAD

**Issue by marataziat** [subfinder/subfinder#162]
You can always register free Censys key, But per month one free account can send only 1000 queries! For an example:
censysApis: ['key1', 'key2']
and subfinder will balance queries between them by using round robin algorithm!

**Comment by codingo** [comment]
We've always gone for a ToS abiding policy to make this safe for usage in pentesting, or professional circumstances. This  couldn't be farther from that, and I would advise purchasing a Censys subscription if you require more requests.
