### ISSUE TITLE
Hackertarget Error

### ISSUE THREAD

**Issue by whoot** [subfinder/subfinder#168]
## What's the problem (or question)?
When using a subdomain for enumeration, the request to hackertarget fails.

## Do you have an idea for a solution?
Either use only the domain and not an additional the subdomain when requesting hackertarget 
or skip the test of hackertarget (as it may produce false positives).

## How can we reproduce the issue?
1. Make request to 'https://api.hackertarget.com/hostsearch/?q=dev.redacted.com'
2. See error message ('error check your search parameter')
3. Make request to 'https://api.hackertarget.com/hostsearch/?q=redacted.com'
4. works.

**Comment by ZeroDot1** [comment]
I can confirm the problem, I get this error with different URLs.

Hi @codingo @picatz @Ice3man543,
Is it possible to solve the problem?, and when will the long announced update come?
I use Subfinder daily and appreciate it very much, I would be very happy about an update...
Thank you for your good work!

**Comment by Ice3man543** [comment]
Hi @ZeroDot1, I am aware of the current issues in subfinder and am working on something much better than the original subfinder, just you know life's life, got busy in some other stuff, so not able to dedicate enough time on this. I promise, in upcoming months, we'll release many great things. You people won't be disappointed for sure!

**Comment by ZeroDot1** [comment]
Hi @Ice3man543,
Thank you very much for your quick answer, I appreciate your work very much, keep up the good work!
We should make an update for the earth so that one day has 48 hours, then we could do more good things... :D

**Comment by Ice3man543** [comment]
@ZeroDot1 seriously, I would love it so much. So much to do, so little time ;)

**Comment by Ice3man543** [comment]
Hey, as far as i am aware, hackertarget doesn't allows recursive enumeration, hence the issue. This is not possible to fix in subfinder, so closing this issue now. Thanks for understanding!

**Comment by whoot** [comment]
uhm.. well maybe you should at least fix subfinder in order to circumvent the error...
as already mentioned:
Either use only the domain and not an additional the subdomain when requesting hackertarget
or skip the test of hackertarget (as it may produce false positives).
