### ISSUE TITLE
Bruteforcing | Only If the subdomains list is very large fails

### ISSUE THREAD

**Issue by 4k4xs4pH1r3** [subfinder/subfinder#172]
## What's the problem (or question)?

When use `-w /usr/share/wordlists/dnsmap.txt`

Only If the subdomains list is very large appear this=

> Starting Bruteforcing of domain.com with 17576 words
> error: open /usr/share/wordlists/dnsmap.txt: too many open files

## Do you have an idea for a solution?
Reproduce the issue at your side and debug.

And Set the feature for use all the wordlists like= `-w /usr/share/wordlists/*.*`

## How can we reproduce the issue?
1. Execute

` ~/go/bin/./subfinder --recursive -d domain.com -b -t 37 -w /usr/share/wordlists/dnsmap.txt -o /root/go/bin/domain_com.json -nW -oT -v`

## What are the running context details?

* Installation method (e.g. `pip`, `apt-get`, `git clone` or `zip`/`tar.gz`): Install from https://github.com/4k4xs4pH1r3/subfinder#direct-installation
* Client OS (e.g. `Microsoft Windows 10`) Kali GNU/Linux Rolling on Windows 10 x86_64
* Program version (see banner): v1.1.3
* Relevant console output (if any):
![image](https://user-images.githubusercontent.com/32862241/63480982-94daa000-c459-11e9-97ff-1c8ac5a4ae95.png)

* Exception traceback (if any):

**Comment by Ice3man543** [comment]
Hey, subfinder is not really the ideal solution for DNS bruteforce. I'll suggest looking into gobuster or massdns! Subfinder is more of a passive subdomain enumeration tool. Thanks for understanding. 

Closing this issue now! If you have any other questions, please don't hesitate to ask!
