### ISSUE TITLE
panic while running job: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by maverickNerd** [subfinder/subfinder#176]
Installed subfinder both with go and git clone master branch:

# go get -u github.com/subfinder/subfinder

# subfinder -d yahoo.com
===============================================
-=Subfinder v1.1.3 github.com/subfinder/subfinder
===============================================

Running Source: Ask
Running Source: Archive.is
Running Source: Baidu
Running Source: Bing
Running Source: CertDB
Running Source: CertificateTransparency
Running Source: Certspotter
Running Source: Commoncrawl
Running Source: Crt.sh
Running Source: Dnsdb
Running Source: DNSDumpster
Running Source: DNSTable
Running Source: Dogpile
Running Source: Exalead
Running Source: Findsubdomains
Running Source: Googleter
Running Source: Hackertarget
Running Source: Ipv4Info
Running Source: PTRArchive
Running Source: Sitedossier
Running Source: Threatcrowd
Running Source: ThreatMiner
Running Source: WaybackArchive
Running Source: Yahoo

Running enumeration on yahoo.com

ipv4info: <nil>

dnsdb: Unexpected return status 404

waybackarchive: parse http://web.archive.org/cdx/search/cdx?url=*.yahoo.com/*&output=json&fl=original&collapse=urlkey&page=: net/url: invalid control character in URL
2019/10/16 13:01:57 panic while running job: runtime error: index out of range [0] with length 0
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: interface conversion: interface {} is runtime.boundsError, not string

goroutine 25 [running]:
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker.func1(0xc00008e8c0)
        /root/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:61 +0x161
panic(0x7ab660, 0xc0002e7da0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/subfinder/subfinder/libsubfinder/sources/dnsdumpster.Query(0xc00000ea00, 0x2, 0x2, 0xc0000213d8, 0x4552c0)
        /root/go/src/github.com/subfinder/subfinder/libsubfinder/sources/dnsdumpster/dnsdumpster.go:61 +0x149c
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker(0xc00008cf00, 0xc00008e8c0)
        /root/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:64 +0x78
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).worker(0xc00008cf00, 0x5)
        /root/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:78 +0xb3
created by github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).Run
        /root/go/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:181 +0x7d

# go version
go version go1.13.1 linux/amd64

# go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build144411569=/tmp/go-build -gno-record-gcc-switches"

**Comment by ddervosj** [comment]
+1 having the same issue...

**Comment by Ice3man543** [comment]
It seems related to #177 , closing this and working on that one
