### ISSUE TITLE
List of resources not working!

### ISSUE THREAD

**Issue by g33kyshivam** [subfinder/subfinder#181]
## What's the problem?
I just saw that there is some issue with some different sources and it seems like one of us could fix it so thought to list down all the sources which have some issues!

## List of the issues with the error message! 

1. **dnsdb**: Unexpected return status 404
2. **waybackarchive**: parse http://web.archive.org/cdx/search/cdx?url=*.example.com/*&output=json&fl=original&collapse=urlkey&page=: net/url: invalid control character in URL
3. **archiveis**: Get http://archive.is/*.example.com: dial tcp 91.121.82.32:80: connect: connection timed out
4. Also, can we have an option for **--recursive** like set the level else it seems to be running in an infinite loop 
I have changed the exact domain with example.com, Rest of the sources seem to be working!

## What are the running context details?

* Installation method: Direct clone and install via go get github.com/subfinder/subfinder
* Client OS: Ubuntu 18.04.2 LTS
* Program version: v1.1.3 
* Relevant console output: Have mentioned with the sources
* Go version: go version go1.13.3 linux/amd64

**Comment by BugMines** [comment]
I'm getting the same problem. Some index out of range error:


dnsdb: Unexpected return status 404
2019/10/27 09:16:58 panic while running job: runtime error: index out of range
panic: runtime error: index out of range [recovered]
	panic: interface conversion: interface {} is runtime.errorString, not string

goroutine 13 [running]:
github.com/subfinder/subfinder/libsubfinder/helper.(*Pool).subworker.func1(0xc0000a45f0)
	/root/go_projects/src/github.com/subfinder/subfinder/libsubfinder/helper/pool.go:61 +0x1c9
panic(0x75e8a0, 0xa96a00)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5

**Comment by Ice3man543** [comment]
Hey, thanks for the heads up. All these will be fixed in the recent release coming soon!
