### ISSUE TITLE
issue while running subfinder

### ISSUE THREAD

**Issue by soupnatzi** [subfinder/subfinder#183]
panic: runtime error: index out of range

i keep getting this issue was wondering if anyone has come across this and fixed i?

goroutine 24 [running]:
github.com/Ice3man543/subfinder/libsubfinder/sources/dnsdumpster.Query(0xc00010a2c0, 0xc0000ac300)
	/root/go/pkg/mod/github.com/!ice3man543/subfinder@v0.1.1/libsubfinder/sources/dnsdumpster/dnsdumpster.go:58 +0xec3
created by github.com/Ice3man543/subfinder/libsubfinder/engines/passive.PassiveDiscovery
	/root/go/pkg/mod/github.com/!ice3man543/subfinder@v0.1.1/libsubfinder/engines/passive/passive.go:223 +0x93f

**Comment by Ice3man543** [comment]
Fixed in latest version!
