### ISSUE TITLE
Multiple domain list input not working correctly 

### ISSUE THREAD

**Issue by Ice3man543** [subfinder/subfinder#34]
The -dl switch is not working correctly. It outputs subdomains for other domains that the one the scan Is being run for. 
This needs to be fixed.

**Comment by Ice3man543** [comment]
If anyone has any ideas, feel free to mention it? @codingo @Mzack9999

**Comment by Mzack9999** [comment]
@Ice3man543 I will work on this and push a fix

**Comment by Ice3man543** [comment]
Yeah @Mzack9999 go ahead. Create a new branch and work on it. Thanks.
