### ISSUE TITLE
Implement DuckDuckGo

### ISSUE THREAD

**Issue by Ice3man543** [subfinder/subfinder#60]

**Comment by kevin6868** [comment]
LETS DO THIS

**Comment by Ice3man543** [comment]
@kevin6868 you are willing to tackle it?

**Comment by Mzack9999** [comment]
Their robots.txt file seems to disallow scraping

[https://duckduckgo.com/robots.txt](https://duckduckgo.com/robots.txt)

**Comment by codingo** [comment]
See: https://duckduckgo.com/api

```
 Because of the way we generate our search results, we unfortunately do not have the rights to fully syndicate our results. For the same reason, we cannot allow framing our results without our branding
```

I think this may be a no-go as I'm unsure even though we attribute the sources in our output if that can be remotely considered branding their responses.
