### ISSUE TITLE
Implementing SubOver or similar subdomain takeover detection! 

### ISSUE THREAD

**Issue by madaratech** [subfinder/subfinder#65]
Hello Guys! 

This is already mentioned in https://github.com/Ice3man543/subfinder/issues/32#issuecomment-386851816, just creating an issue here, so it's trackable. 

Best way for this would be with flag like `-takeover`  or `-to` (to == take over)

`./subfinder -d test.com -nW -takeover`

**Comment by Ice3man543** [comment]
Hey @madaratech,
I thought about it. In my honest opinion, adding takeover detection would make the tool redundant. I mean, it's a completely different task. I am currently working on other stuff. Once i get some time, probably tomorrow, i will work on the issues currently. Now, i am marking this is as possible enhancement.
Thanks you.

**Comment by madaratech** [comment]
Sure, thank you.

**Comment by codingo** [comment]
Closing this as it's not being actively worked on and we're focussing mostly on just doing subdomain enumeration as good as possible.

If this changes we'll re-open this issue in the future.
